# -*- coding: utf-8 -*-
"""DL_Sentiment_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FuGrw-TB3E0QITLVSU8Rdn5XRZMqe-Ef
"""

import pandas as pd
import numpy as np
import re
import time
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Conv1D, MaxPooling1D, LSTM, GRU, Dense, Dropout, SpatialDropout1D
from tensorflow.keras.callbacks import EarlyStopping

# STEP 1: LOAD DATA
df = pd.read_csv('tweets.csv')

# STEP 2: CLEANING
def clean_text(text):
    text = text.lower()
    text = re.sub(r'http\S+|www\S+', '', text)
    text = re.sub(r'@\w+', '', text)
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    return re.sub(r'\s+', ' ', text).strip()

df['cleaned_text'] = df['text'].apply(clean_text)

# STEP 3: LABEL ENCODING
le = LabelEncoder()
y = le.fit_transform(df['airline_sentiment'])

# STEP 4: TOKENIZATION
max_features = 10000
max_len = 100

tokenizer = Tokenizer(num_words=max_features, oov_token="<OOV>")
tokenizer.fit_on_texts(df['cleaned_text'])

X = tokenizer.texts_to_sequences(df['cleaned_text'])
X = pad_sequences(X, maxlen=max_len)

# STEP 5: TRAIN TEST SPLIT
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# STEP 6: MODEL FUNCTION
def build_model(model_type='LSTM'):
    model = Sequential([
        Embedding(max_features, 128, input_length=max_len),
        SpatialDropout1D(0.2),
        Conv1D(64, 5, activation='relu'),
        MaxPooling1D(pool_size=4),

        LSTM(64, dropout=0.2, recurrent_dropout=0.2)
        if model_type == 'LSTM'
        else GRU(64, dropout=0.2, recurrent_dropout=0.2),

        Dense(3, activation='softmax')
    ])

    model.compile(
        loss='sparse_categorical_crossentropy',
        optimizer='adam',
        metrics=['accuracy']
    )

    return model

# STEP 7: CALLBACK
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=2,
    restore_best_weights=True
)

# STEP 8: TRAIN CNN-LSTM
print("Training CNN-LSTM...")
cnn_lstm = build_model('LSTM')

start = time.time()
history_lstm = cnn_lstm.fit(
    X_train, y_train,
    epochs=10,
    batch_size=64,
    validation_split=0.1,
    callbacks=[early_stop]
)
lstm_time = time.time() - start

# STEP 9: TRAIN CNN-GRU
print("\nTraining CNN-GRU...")
cnn_gru = build_model('GRU')

start = time.time()
history_gru = cnn_gru.fit(
    X_train, y_train,
    epochs=10,
    batch_size=64,
    validation_split=0.1,
    callbacks=[early_stop]
)
gru_time = time.time() - start

# STEP 10: EVALUATION
def evaluate(model, name):
    y_pred = np.argmax(model.predict(X_test), axis=1)
    acc = accuracy_score(y_test, y_pred)

    print(f"\n{name} Accuracy: {acc:.4f}")
    print(classification_report(y_test, y_pred, target_names=le.classes_))

    return acc, y_pred

acc_lstm, y_pred_lstm = evaluate(cnn_lstm, "CNN-LSTM")
acc_gru, y_pred_gru = evaluate(cnn_gru, "CNN-GRU")

# STEP 11: CONFUSION MATRIX
def plot_cm(y_true, y_pred, title):
    cm = confusion_matrix(y_true, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=le.classes_,
                yticklabels=le.classes_)
    plt.title(title)
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()

plot_cm(y_test, y_pred_lstm, "CNN-LSTM Confusion Matrix")
plot_cm(y_test, y_pred_gru, "CNN-GRU Confusion Matrix")

# STEP 12: LEARNING CURVES
def plot_history(history, title):
    plt.plot(history.history['accuracy'], label='Train')
    plt.plot(history.history['val_accuracy'], label='Validation')
    plt.title(title)
    plt.xlabel("Epochs")
    plt.ylabel("Accuracy")
    plt.legend()
    plt.show()

plot_history(history_lstm, "CNN-LSTM Accuracy")
plot_history(history_gru, "CNN-GRU Accuracy")

# STEP 13: COMPARISON
plt.bar(['CNN-LSTM', 'CNN-GRU'], [acc_lstm, acc_gru])
plt.title("Accuracy Comparison")
plt.ylabel("Accuracy")
plt.show()

# STEP 14: COMPLEXITY
def model_complexity(model, name):
    params = model.count_params()
    print(f"{name} Parameters: {params}")
    return params

params_lstm = model_complexity(cnn_lstm, "CNN-LSTM")
params_gru = model_complexity(cnn_gru, "CNN-GRU")

print("\nFINAL COMPARISON")
print(f"LSTM Accuracy: {acc_lstm:.4f}, Time: {lstm_time:.2f}s")
print(f"GRU Accuracy: {acc_gru:.4f}, Time: {gru_time:.2f}s")